# 配置zuul路由
server:
  port: 80
spring:
  application:
    name: service-zuul

# eureka 注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8750/eureka/

# 路由规则
zuul:
  routes:
    client1:
      path: /client1/**
      serviceId: client1
    client2:
      path: /client2/**
      serviceId: client2