# 单节点注册中心server
spring:
  application:
    name: server

server:
  port: 8750

eureka:
#  server:
#    enableSelfPreservation: true
  instance:
    hostname: localhost
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/