# 本身作为生产者启动（向注册中心注册）

server:
  port: 8755

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8750/eureka/